[package]
name = "cn"
version = "0.1.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#clap={"3.2.17",features=["derive"]}
cargo-util="0.2.1"
mylibrary={git="https://github.com/sugiura-hiromichi/mylibrary"}
